name: frontend_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_auth: ^3.6.2
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  equatable: ^2.0.3
  firebase_core: ^1.20.0
  google_fonts: ^3.0.1
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  url_launcher: ^6.1.5
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

  flutter_native_splash: ^2.2.7
  flutter_launcher_icons: "^0.9.2"


flutter_native_splash:
  color: "#ffffff"
  image: Assets/Images/logo.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "Assets/Images/logo.png"


flutter:


  uses-material-design: true

 
  assets:
    - Assets/Images/
    - Assets/Json/
